// angular-src/src/app/components/home/home.component.ts
/* Home Component: Landing Page for Website Description
 * As well as some small navigation and suggestions such as
 * what the website does for the user as well as 
 * the directing the user to register and login.
 * 
 * 
*/

import { Component, OnInit } from '@angular/core';
declare const $: any;
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }
//Insert Javascript/Jquery - in this case toggle the navbar on clicks of changing page
  ngAfterContentInit() {
        $(document).ready(function() {
                $('.parallax').parallax();
        });
  }

}

<div class ="text-center">
  <div class="header center"><h6>Under Development</h6></div>
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot no-pad-top">
      <div class="container">
        <br /><br />
        <h2 class= "header title center red-text text-lighten-2 ">Dealbreaker Dating</h2>
        <div class="row center">
          <h5 class="header col s12 white-text slogan darken-6 "> Know before you start! </h5>
        </div>
        <br><br>
      </div>
      </div>
      <div id="showcase-img" class="parallax"><img  class="responsive-img" src="../../assets/images/home.jpg" alt="Unsplashed background img 1"></div>
      <div class="row center">
          <a *ngIf="!authService.loggedIn()" id="home-reg" class = "btn btn-large button-front-right red waves-effect waves-light  button-head" data-position="bottom" data-delay="50" data-tooltip="Register Page" [routerLink]="['/register']">Register</a> 
          <a *ngIf="!authService.loggedIn()" id="home-login"  class = "btn waves-effect button-front-left pink waves-light btn-large button-head" data-position="bottom" data-delay="50" data-tooltip="Login Page" [routerLink]="['/login']">Login</a>
           <a *ngIf="authService.loggedIn()" id="home-reg" class = "btn btn-large button-front-right red waves-effect waves-light  button-head" data-position="bottom" data-delay="50" data-tooltip="Find your match!" [routerLink]="['/browse']">Browse</a> 
          <a *ngIf="authService.loggedIn()" id="home-login"  class = "btn waves-effect button-front-left pink waves-light btn-large button-head" data-position="bottom" data-delay="50" data-tooltip="Manage Relationships" [routerLink]="['/dashboard']">Dashboard</a>  
      </div>
  </div>
  <ul class="main container-fluid">
    <li>
      <section>
        <div class="container">
          <div class="row center">
            <img id="match" class="responsive-img" src="../../assets/svg/couple.svg" alt="">
          <h5 class="center heading">Find Your Match!</h5>
          <p class="center desc center-focus bold flow-text"> Each person lists their interests and what they are looking for in their potential matches. However, each profile also contains their deal breakers, to help make a better and quicker descision.
          </p>
        </div>
        </div>
      </section>
    </li>
    <li>
      <section>
        <div  class="container"> 
          <div class = "row center">
            <img id="community" class="responsive-img" src="../../assets/svg/community.svg" alt="">
              <h5  class="center heading">Community Feedback</h5>      
              <p class="center desc center-focus bold flow-text">
                Users are able to give feedback on each other by commenting on the user's profile, available for other potential matches to see. This is not a forum for bullying, but will help prevent the creation of malicious profiles.
              </p>
          </div>
        </div>
      </section>
      </li>
    <li>
      <section>
        <div class="container">
          <div class="row center">
              <img id="quickEasy" class="responsive-img" src="../../assets/svg/fast.svg" alt="">
          <h5 class="center heading"> Quick and Easy </h5>    
          <p class="center desc center-focus bold flow-text"> 
            Simply browse for users to find your potential match, or navigate to their profile by username. Once added, you can set up dates through messages or exchange contact information and keep it completely private.
          </p>    
          </div>
        </div>
      </section>
    </li>
    <li>    
      <section id = "donate" >
        <div class="container">
          <div class = "row center">
            <img id="quickEasy" class="responsive-img" src="../../assets/svg/donation.svg" alt="" />
            <br />
            <br />
          <h5 class="center heading"> Free and Open </h5>    
          <p class="center desc center-focus bold flow-text"> 
            Dealbreaker is a free and open source dating website, supported by the user's choice to donate.
          </p>
          </div>
        </div>
      </section>
    </li>
  </ul>
</div>

// react-src/src/components/Home.js
import React, { Component } from 'react';
import { reduxForm } from 'redux-form';

class Home extends Component {

    constructor(){
        super();
        this.state = {

        }
    }

    handleSubmit(){


    }

    render(){
        
        return(

           <div className = "jumbotron text-center">
  <div id="index-banner" className="parallax-container">
    <div className="section no-pad-bot no-pad-top">
      <div className="container">
        <br /><br />
          <h1 className= "center">Dealbreaker</h1>
        <div className="row center">
          <h4 className="header slogan"> Know before you start! </h4>
        </div>
        <br /><br />
      </div>
    </div>
    <div className="parallax"><img className=" front-img responsive-img" src="https://static.pexels.com/photos/6541/sea-man-beach-holiday.jpg" alt="Unsplashed background img 1" /></div>
  <div className="row center">
           <button className = "btn btn-primary btn-lg">Register</button> 
            <button className = "btn btn-primary btn-lg">Login</button>  
        </div>
  
  </div>
<div className = "container row-center">
  <div className="">
      <h3 className="center">Community Feedback</h3>      
      <p className="center">Users are able to give Feedback on each other by commenting on the user's profile available for other potential matches to see. This is not a forum for bullying, rather to weed out malicious profiles that are not using the website seriously.
      </p>
  </div>
  <div className="">
      <h3 className="center heading">Find Your Match!</h3>
      <p className="center"> Each person lists their qualities and attributes for the each potential match but only their bad attributes and deal breakers are visible until being confirmed. This lets the user know what they are in for with the added suspense of discovering their matches best attributes, however a short biography is included to give each user's profile a personality.
       </p>
  </div>
  <div className="">
      <h3 className="center"> Quick and Easy </h3>    
      <p className="center "> Simply browse for users to find your potential match, or navigate to their profile by username. Once added you can set up dates through messages or exchange contact information and keep it completly private, as well as sharing private images for each other to see.</p>
      
  </div>
</div>
</div>
                
        );


    }



}

export default Home;
